/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DropdownOption = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const Member = IDL.Record({
  'id' : IDL.Text,
  'assemblyId' : IDL.Text,
  'memberId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'districtId' : IDL.Text,
  'address' : IDL.Text,
  'unionId' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDropdownOption' : IDL.Func([IDL.Text, IDL.Text], [DropdownOption], []),
  'addMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Member],
      [],
    ),
  'deleteDropdownOption' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getDropdownOptions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DropdownOption)],
      ['query'],
    ),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'searchMembers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Member)],
      ['query'],
    ),
  'seedInitialData' : IDL.Func([], [], []),
  'updateDropdownOption' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(DropdownOption)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DropdownOption = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const Member = IDL.Record({
    'id' : IDL.Text,
    'assemblyId' : IDL.Text,
    'memberId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'districtId' : IDL.Text,
    'address' : IDL.Text,
    'unionId' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    'addDropdownOption' : IDL.Func([IDL.Text, IDL.Text], [DropdownOption], []),
    'addMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Member],
        [],
      ),
    'deleteDropdownOption' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getDropdownOptions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DropdownOption)],
        ['query'],
      ),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'searchMembers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Member)],
        ['query'],
      ),
    'seedInitialData' : IDL.Func([], [], []),
    'updateDropdownOption' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(DropdownOption)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };