/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DropdownOption {
  'id' : string,
  'text' : string,
  'category' : string,
}
export interface Member {
  'id' : string,
  'assemblyId' : string,
  'memberId' : string,
  'name' : string,
  'createdAt' : Time,
  'districtId' : string,
  'address' : string,
  'unionId' : string,
  'mobile' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addDropdownOption' : ActorMethod<[string, string], DropdownOption>,
  'addMember' : ActorMethod<
    [string, string, string, string, string, string, string],
    Member
  >,
  'deleteDropdownOption' : ActorMethod<[string], boolean>,
  'getDropdownOptions' : ActorMethod<[string], Array<DropdownOption>>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'searchMembers' : ActorMethod<[string, string], Array<Member>>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'updateDropdownOption' : ActorMethod<[string, string], [] | [DropdownOption]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];